#include <stdio.h>

int main() {
    FILE *htmlFile;

    // Open a file in write mode
    htmlFile = fopen("output.html", "w");

    if (htmlFile == NULL) {
        printf("Error opening file!\n");
        return 1;
    }

    // Write HTML content to the file
    fprintf(htmlFile, "<!DOCTYPE html>\n");
    fprintf(htmlFile, "<html>\n");
    fprintf(htmlFile, "<head>\n");
    fprintf(htmlFile, "<title>Generated by C</title>\n");
    fprintf(htmlFile, "</head>\n");
    fprintf(htmlFile, "<body>\n");
    fprintf(htmlFile, "<h1>Hello, World!</h1>\n");
    fprintf(htmlFile, "<p>This HTML file was generated by a C program.</p>\n");
    fprintf(htmlFile, "</body>\n");
    fprintf(htmlFile, "</html>\n");

    // Close the file
    fclose(htmlFile);

    printf("HTML file generated successfully.\n");

    return 0;
}